#+TITLE: README
* ასემბლი
** ჰენდაუთი 12 computer architecture
| 1-2 გვერდი, Load-მდე
სურათი რაცაა პირველ გვერდზე, ამის დამოუკიდებლად გახსენება, თითოეული კავშირი რას
ნიშნავს. დამატებითი კითხვები:
*** პროცესორში მონაცემთა შემნახველს რა ეწოდება და თითოეული რამდენ სიტყვას ინახავს?
რეგისტრი, ერთი
*** cpu ს აბსტრაქცია რა არის?
ანუ რა "ინტერფეისს" გვთავაზობს
მიწოდებულ ინსტრუქციებს ახორციელებს ერთმანეთის მიყოლებით, მიმდევრობის დაცვით
თუ გვინდა რომ რამდენიმე პროგრამა ერთმანეთს ეცვლებოდეს და პარალელიზმს მივაღწიოთ,
software levelზე უნდა გავაკეთოთ ეს
*** რა ინსტრუქციების განხორციელება შეგვიძლია
Load/Store - ბაიტების მოძრაობა მეხსიერებასა და რეგისტრებს შორის
Branch/jump - მომდევნო ინსტრუქციის შეცვლა
*** დავალება: ჰენდაუთის თავიდან ბოლომდე წაკითხვა
** ჰენდაუთი 13 გვერდი 1-2
| 1-3 გვერდი, more type conversions-მდე
ამ ჰენდაუთში რა კოდებიც წერია, ისინი დაფასთან (c კოდის ესემბლიში გადაყვანა). ჯერ
კომენტარები რაც უწერია ეგ, სიტყვებით, შემდეგ შესაბამისი ინსტრუქციის მიწერა.
pdf-ში არის ჰაილაითები ტერმინები და შენიშვნებისთვის
*** დავალება: ჰენდაუთის თავიდან ბოლომდე წაკითხვა
